apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalayer-{{ .Release.Name }}
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "explorer.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        kuber-role: master
      containers:
        - name: explorer
          image: {{ .Values.kuber.image }}
          imagePullPolicy: {{ .Values.kuber.imagePullPolicy }}
          ports:
            - containerPort: 9091
              name: web
          env:
            - name: APISERVER_HOST
              value: ""
            - name: GOOGLE_API_KEY
              value: "{{ .Values.google.apiKey }}"
            - name: GOOGLE_CLIENT_ID
              value: "{{ .Values.google.clientId }}"
            - name: GOOGLE_REDIRECT
              value: "{{ .Values.google.redirect }}"
            - name: GOOGLE_SECRET
              value: "{{ .Values.google.secret }}"
            - name: GOOGLE_SCOPE
              value: "{{ .Values.google.scope }}"
            - name: HDFS
              value: "{{ .Values.hdfs }}"
            - name: KUBER_AUTOSCALING
              value: "{{ .Values.kuber.autoScaling }}"
            - name: KUBER_UI
              value: "{{ .Values.kuber.board }}"
            - name: KUBER_INSECURE_BIND_ADDRESS
              value: "{{ .Values.kuber.insecureBindAddress }}"
            - name: KUBER_REST
              value: "{{ .Values.kuber.rest }}"
            - name: KUBER_WS
              value: "{{ .Values.kuber.ws }}"
            - name: MICROSOFT_APPLICATION_ID
              value: "{{ .Values.microsoft.applicationId }}"
            - name: MICROSOFT_REDIRECT
              value: "{{ .Values.microsoft.redirect }}"
            - name: MICROSOFT_SECRET
              value: "{{ .Values.microsoft.secret }}"
            - name: MICROSOFT_SCOPE
              value: "{{ .Values.microsoft.scope }}"
            - name: SPITFIRE_REST
              value: "{{ .Values.spitfire.rest }}"
            - name: SPITFIRE_WS
              value: "{{ .Values.spitfire.ws }}"
            - name: TWITTER_CONSUMER_KEY
              value: "{{ .Values.twitter.consumerKey }}"
            - name: TWITTER_CONSUMER_SECRET
              value: "{{ .Values.twitter.consumerSecret }}"
            - name: TWITTER_REDIRECT
              value: "{{ .Values.twitter.redirect }}"
          resources:
{{ toYaml .Values.kuber.resources | indent 12 }} 
          readinessProbe:
            httpGet:
              path: /
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 1
        - name: explorer-sidecar
          image: datalayer/k8s-sidecar:1.8.2
          imagePullPolicy: IfNotPresent
          args: ["proxy", "-p", "8001"]
