apiVersion: v1
kind: Service
metadata:
{{- if .Values.controller.service.annotations }}
  annotations:
{{ toYaml .Values.controller.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: controller
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.controller.service.labels }}
{{ toYaml .Values.controller.service.labels | indent 4 }}
  {{- end }}
  name: {{ template "controller.fullname" . }}
spec:
  ports:
    - port: 8080
  selector:
    app: {{ template "name" . }}
    component: controller
    release: {{ .Release.Name }}
