zeppelin:
  image: datalayer/zeppelin-k8s:2.2.0-0.5.0
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      memory: "4096Mi"
      cpu: "2000m"
hdfsK8s:
  useConfigMap: false
  configMapName: zeppelin-k8s-hdfs-locali
  configPath: /etc/hdfs-k8s/conf
  nameNodeUri: hdfs://hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local:8020
spark:
  driverMemory: 1g
  executorMemory: 1g
  numExecutors: 2
