apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kuber
  labels:
    app: {{ template "kuber.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "kuber.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kuber-role
                operator: NotIn
                values:
                - master
      containers:
        - name: kuber
          image: {{ .Values.kuber.image }}
          imagePullPolicy: {{ .Values.kuber.imagePullPolicy }}
          volumeMounts:
          resources:
{{ toYaml .Values.kuber.resources | indent 12 }} 
        - name: kuber-sidecar
          image: datalayer/k8s-sidecar:1.8.2
          imagePullPolicy: IfNotPresent
          args: ["proxy", "-p", "8001"]
