## nginx configuration
## Ref: https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress

defaultBackend:
  enabled: true

controller:
#  defaultBackendService: "default/explorer-kuber"
  hostNetwork: false
  nodeSelector:
    kuber-role: "master"

# tcp:
#  81: "default/spitfire-spitfire:8080"
