defaultBackend:
  enabled: true
controller:
#  defaultBackendService: "default/explorer-kuber"
  hostNetwork: false
  nodeSelector:
    kuber-role: "master"
  service:
    annotations: {
      "kubernetes.io/ingress.class": "nginx",
      "ingress.kubernetes.io/ssl-redirect": "true",
      "service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout": "3600",
      "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "*",
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tcp",
      #"service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": '*',
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:us-west-2:100392638540:certificate/faa2bfbf-ff19-4e12-9bbe-220af0b77146",
      #"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags": "kuber-role=explorer"
    }
# tcp:
#  81: "default/spitfire-spitfire:8080"
