defaultBackend:
  enabled: true
controller:
#  defaultBackendService: "default/explorer-kuber"
  hostNetwork: false
  nodeSelector:
    kuber-role: "master"
  service:
    annotations: {
      "kubernetes.io/ingress.class": "nginx",
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "https",
      "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "https",
      "service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags": "kuber-role=explorer",
      "ingress.kubernetes.io/ssl-redirect": "true"
    }
# tcp:
#  81: "default/spitfire-spitfire:8080"
