apiVersion: v1
description: Web-based Data Explorer that enables data-driven, interactive data analytics and collaborative documents.
name: explorer
version: 0.0.1
appVersion: 0.0.1
home: https://datalayer.io
sources:
- https://github.com/datalayer/explorer
icon: http://datalayer.io/img/logo-datalayer-horizontal.png
maintainers:
- name: eric
  email: eric@datalayer.io
