apiVersion: v1
description: Web-based notebook that enables data-driven, interactive data analytics and collaborative documents.
name: spitfire
version: 1.0.0
appVersion: 0.7.3
home: https://datalayer.io
sources:
- https://github.com/datalayer-contrib/spitfire
icon: http://datalayer.io/img/logo-datalayer-horizontal.png
maintainers:
- name: eric
  email: eric@datalayer.io
