spitfire:
  image: datalayer/spitfire:latest
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      memory: "8192Mi"
      cpu: "3000m"
hdfsK8s:
  useConfigMap: true
  configMapName: hdfs-k8s-hdfs-k8s-hdfs-dn
  configPath: /etc/hdfs-k8s/conf
spark:
  driverMemory: 8g
  executorMemory: 8g
  numExecutors: 3
